return {
    Position    = require(_G.componentsDir .. "component-position"),
    Orientation = require(_G.componentsDir .. "component-orientation"),
    Dimension   = require(_G.componentsDir .. "component-dimension"),
    Agility     = require(_G.componentsDir .. "component-agility"),
    Brain       = require(_G.componentsDir .. "component-brain"),
    Clan        = require(_G.componentsDir .. "component-clan"),
    Energy      = require(_G.componentsDir .. "component-energy"),
    Eye         = require(_G.componentsDir .. "component-eye"),
    Distance    = require(_G.componentsDir .. "component-distance"),
    Fame        = require(_G.componentsDir .. "component-fame"),
    Force       = require(_G.componentsDir .. "component-force"),
    Hand        = require(_G.componentsDir .. "component-hand"),
    Intelligence= require(_G.componentsDir .. "component-intelligence"),
    Life        = require(_G.componentsDir .. "component-life"),
    Parent      = require(_G.componentsDir .. "component-parent"),
    Child       = require(_G.componentsDir .. "component-child"),
    Name        = require(_G.componentsDir .. "component-name"),
    Owner       = require(_G.componentsDir .. "component-owner"),
    Player      = require(_G.componentsDir .. "component-player"),
    Quest       = require(_G.componentsDir .. "component-quest"),
    Shield      = require(_G.componentsDir .. "component-shield"),
    Speed       = require(_G.componentsDir .. "component-speed"),
    Wallet      = require(_G.componentsDir .. "component-wallet"),
}